<?php

namespace AppBundle\Repository;

/**
 * CollabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollabRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllCollab($user): array
    {
        $qb = $this->createQueryBuilder('c')
                ->leftJoin('c.userTo', 'usrTo')
                ->leftJoin('c.notes', 'notes', 'WITH', 'notes.userFrom = :user AND notes.status = false')
                ->addSelect('usrTo')
                ->addSelect('notes')
                ->where('c.userFrom = :user')
                ->orWhere(':user MEMBER OF c.userTo')
                    ->setParameter('user', $user)
                ->orderBy('c.startedAt', 'DESC');

        return $qb->getQuery()->getResult();
    }

    public function getIndexCollab(): array
    {
        $qb = $this->createQueryBuilder('c')
                ->leftJoin('c.userFrom', 'uFrom')
                ->leftJoin('c.userTo', 'uTo')
                ->leftJoin('c.notes', 'notes', 'WITH', 'notes.status = true')
                ->addSelect('uFrom')
                ->addSelect('uTo')
                ->addSelect('notes')
                ->leftJoin('uTo.collabRequest', 'uToColReq')
                ->orderBy('c.startedAt', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
