<?php

namespace AppBundle\Repository;

/**
 * CollabRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollabRequestRepository extends \Doctrine\ORM\EntityRepository
{
    public function findInvitation($id): array
    {
        $qb = $this->createQueryBuilder('cr')
                ->leftJoin('cr.user', 'usr')
                ->where('usr.id = :id')
                ->setParameter('id', $id)
                ->andWhere('cr.isAccepted = :bool')
                ->setParameter('bool', false)
                ->andWhere('cr.isRefused = :bool')
                ->setParameter('bool', false);

        return $qb->getQuery()->getResult();
    }

    public function findUserInvitation($id): array
    {
        $qb = $this->createQueryBuilder('cr')
                ->leftJoin('cr.user', 'usr')
                ->where('usr.id = :id')
                ->setParameter('id', $id)
                ->andWhere('cr.isAccepted = :bool')
                ->setParameter('bool', false)
                ->andWhere('cr.isRefused = :bool')
                ->setParameter('bool', false)
                ->leftJoin('cr.collab', 'col')
                ->addSelect('col')
                ->leftJoin('col.userTo', 'uto')
                ->addSelect('uto');

        return $qb->getQuery()->getResult();
    }
}
