<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findUserByKeyword($keyword)
    {
        $qb = $this->createQueryBuilder('u')
                ->where('REGEXP(u.username, :regexp) = true')
                ->setParameter('regexp', $keyword)
                ->leftJoin('u.skill', 'skl')
                ->addSelect('skl');

        return $qb->getQuery()->getArrayResult();
    }
}
